
---
version: "1.17.1"

volumes:
  data:
    driver: local
    driver_opts:
      type: volumes
      device: /var/lib/docker/volumes/data
      o: bind

  musik:
    driver: local
    driver_opts:
      type: volumes
      device: /var/lib/docker/volumes/musik
      o: bind

  filme:
    driver: local
    driver_opts:
      type: volumes
      device: /var/lib/docker/volumes/filme
      o: bind

  serien:
    driver: local
    driver_opts:
      type: volume
      device: /var/lib/docker/volumes/serien
      o: bind

services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    container_name: plexjanis
    restart: unless-stopped
    ports:
      - 32400:32400
      - 32400:32400/udp

    volumes:
      - /home/ubuntu/data/plexmueller/config:/medien/config
      - /home/ubuntu/data/plexmueller/musik:/medien/musik
      - /home/ubuntu/data/plexmueller/serien:/medien/serien
      - /home/ubuntu/data/plexmueller/filme:/medien/filme

    environment:
      - TZ=Europe/Zuerich
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - PLEX_CLAIM=claim-zJFf5udVzmdBLk_MuTys
