---
version: "3.4"

volumes:
  data:
    driver: local
    driver_opts:
      type: volumes
      device: /mnt/config
      o: bind

  musik:
    driver: local
    driver_opts:
      type: volumes
      device: /var/lib/docker/volumes/musik
      o: bind

  filme:
    driver: local
    driver_opts:
      type: volumes
      device: /var/lib/docker/volumes/filme
      o: bind

  serien:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/docker/volumes/serien
      o: bind

services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    container_name: plexjanis
    restart: unless-stopped
    ports:
      - 32400:32400
      - 32400:32400/udp

    volumes:
      - data:/home/ubuntu/data/plexmueller/config
      - musik:/home/ubuntu/data/plexmueller/musik
      - serien:/home/ubuntu/data/plexmueller/serien
      - filme:/home/ubuntu/data/plexmueller/filme

    environment:
      - TZ=Europe/Zuerich
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - PLEX_CLAIM=claim-iEKfocShwkEAgyjgTY1P
